server:
  port: 8081
  servlet:
    context-path: /water-map-api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.26:5432/mphgis
    username: postgres
    password: 1111
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.water.map.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO

# 自定义配置
app:
  upload-path: D:\data\files\
  allowed-origins: http://localhost:5173,http://localhost:8080,http://127.0.0.1:5173